
# Workflow to scan the latest container image periodically
name:  CFX Scheduled Daily Trivy Latest

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/cfx-trivy.yaml'
  schedule:
    # Daily
    - cron: '0 0 * * *'

concurrency:
  # cancel older running jobs on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan-image:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write

    strategy:
      matrix:
        include:
          - service_name: ssi-credential-issuer-service
          - service_name: ssi-credential-issuer-migrations
          - service_name: ssi-credential-issuer-processes-worker
          - service_name: ssi-credential-expiry-app

    uses: Cofinity-X/central-pipelines/.github/workflows/reusable-trivy-acr-latest-image-scan.yaml@main
    name: Trivy Scan
    with:
      environment: lower-env-acr
      image-name: ${{ matrix.service_name }}
      image-namespace: core-services/ssi-issuer/images
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}